group:
  - repos: |
      jacquindev/windots
      jacquindev/automated-wsl2-setup
    files:
      - source: LICENSE
        dest: LICENSE
        replace: false

  - repos: |
      jacquindev/automated-wsl2-setup
    files:
      - source: Brewfile
        dest: Brewfile

  - repos: |
      jacquindev/windots
    files:
      - source: .config/yazi/
        dest: config/yazi/
      - source: .czrc
        dest: home/.czrc
      - source: gitalias.txt
        dest: config/gitaliases
      - source: .config/starship.toml
        dest: config/starship.toml
