group:
  - repos: |
      jacquindev/windots
      jacquindev/automated-wsl2-setup
    files:
      - source: LICENSE
        dest: LICENSE

  - repos: |
      jacquindev/automated-wsl2-setup
    files:
      - source: Brewfile
        dest: Brefile

  - repos: |
      jacquindev/windots
    files:
      - source: .config/yazi/
        dest: config/yazi/
      - source: .czrc
        dest: home/.czrc
