tap "homebrew/bundle"

brew "bat"
brew "btop"
brew "dua-cli"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "git-delta"
brew "git-extras"
brew "git-lfs"
brew "jq"
brew "lazygit"
brew "luarocks"
brew "neovim"
brew "ripgrep"
brew "shellcheck"
brew "starship"
brew "stow"
brew "tealdeer"
brew "vfox"
brew "wrk"
brew "yazi"
brew "yq"
brew "zoxide"

tap "hashicorp/tap"

brew "hashicorp/tap/terraform"
brew "hashicorp/tap/vagrant"
brew "hashicorp/tap/vault"
brew "hashicorp/tap/packer"

tap "kubescape/tap"

brew "helm"
brew "kubernetes-cli"
brew "kubescape/tap/kubescape-cli"
brew "minikube"
