version: 1
git_protocol: https
editor: nvim
prompt: enabled
prefer_editor_prompt: disabled
pager: delta

aliases:
    co: pr checkout
    dl: download    # extension: yuler/gh-download
    prs: f -p       # extension: gennaro-tedesco/gh-f
    l: f -l         # extension: gennaro-tedesco/gh-f

http_unix_socket:
browser:

# Catppuccin Macchiato theme
theme:
    colors:
        text:
            primary: "#cad3f5"
            secondary: "#c6a0f6"
            inverted: "#181926"
            faint: "#b8c0e0"
            warning: "#eed49f"
            success: "#a6da95"
            error: "#ed8796"
        background:
            selected: "#363a4f"
        border:
            primary: "#c6a0f6"
            secondary: "#494d64"
            faint: "#363a4f"
