# The current version of the config schema
version: 1
# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# Preference for editor-based interactive prompting. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prefer_editor_prompt: disabled
# A pager program to send command output to, e.g. "less". If blank, will refer to environment. Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for gh commands
aliases:
    co: pr checkout
# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
# What web browser gh should use when opening URLs. If blank, will refer to environment.
browser:
# Catppuccin Macchiato theme
theme:
    colors:
        text:
            primary: "#cad3f5"
            secondary: "#c6a0f6"
            inverted: "#181926"
            faint: "#b8c0e0"
            warning: "#eed49f"
            success: "#a6da95"
            error: "#ed8796"
        background:
            selected: "#363a4f"
        border:
            primary: "#c6a0f6"
            secondary: "#494d64"
            faint: "#363a4f"
