github.com:
    users:
        jacquindev:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: jacquindev
