#!/bin/sh
if ! command -v "brew" >/dev/null 2>&1; then return; fi

alias ba='brew autoremove'
alias bc='brew cleanup'
alias bi='brew install'
alias bl='brew list'
alias bo='brew outdated'
alias bu='brew uninstall'
alias bubo='brew update && brew outdated'
alias bubu='bubo && brew upgrade'
alias bupd='brew update'
alias bupg='brew upgrade'

brews() {
    formulae=$(brew leaves | xargs brew deps --installed --for-each)
    casks=$(brew list --cask 2>/dev/null)

    green="$(tput setaf 2)"
    magenta="$(tput setaf 5)"
    cyan="$(tput setaf 6)"
    bold="$(tput bold)"
    off="$(tput sgr0)"

    printf "%s==>%s %sFormulae%s\n" "$green" "$magenta" "$bold" "$off"
    echo "$formulae" | sed "s/^\(.*\):\(.*\)$/\1${cyan}\2${off}/"
    printf "\n%s==>%s %sCasks%s\n" "$green" "$magenta" "$bold" "$off"
    echo "$casks"
}
