#!/bin/sh
if command -v eza > /dev/null 2>&1; then 
    alias ls='eza --git --icons --group --group-directories-first --time-style=long-iso --color-scale=all'
    alias l='ls --git-ignore'
    alias ll='ls --all --header --long'
    alias llm='ls --all --header --long --sort=modified'
    alias la='ls -lbhHigUmuSa'
    alias lx='ls -lbhHigUmuSa@'
    alias lt='eza --all --icons --group --group-directories-first --tree --color-scale=all'
    alias tree='ls --tree'
else
    alias ls='ls --color=auto'
    alias ll='ls -alF'
    alias la='ls -A'
    alias l='ls -CF'
fi
