# yaml-language-server: $schema=https://json.schemastore.org/lazydocker.json

gui:
  language: "en"
  border: "rounded"
  theme:
    activeBorderColor:
      - "#eba0ac"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    selectedLineBgColor:
      - "#313244"
    optionsTextColor:
      - "#89b4fa"
