#!/bin/bash
export DOTFILES="$HOME/.dotfiles"

[ -f "$DOTFILES/shared/envs" ] && source "$DOTFILES/shared/envs"
[ -f "$DOTFILES/shared/paths" ] && source "$DOTFILES/shared/paths"
[ -f "$DOTFILES/shared/brew" ] && source "$DOTFILES/shared/brew"

# shared folder
for file in "$DOTFILES/shared/config/"*; do
    source "$file"
done
unset file

# Oh-my-posh
if command -v "oh-my-posh" >/dev/null 2>&1; then
    eval "$(oh-my-posh init bash --config $(brew --prefix oh-my-posh)/themes/hunk.omp.json)"
fi

# Histfile
[ -d "$HOME/.cache/bash" ] || mkdir -p "$HOME/.cache/bash"
[ -f "$HOME/.bash_history" ] && mv -i "$HOME/.bash_history" "$HOME/.cache/bash/bash_history"

HISTFILE=/home/$USER/.cache/bash/bash_history

# Oh-my-bash
export OSH="$XDG_DATA_HOME/bash/oh-my-bash"

#OSH_THEME="powerbash10k"
DISABLE_AUTO_UPDATE=true
DISABLE_UNTRACKED_FILES_DIRTY="true"
SCM_GIT_DISABLE_UNTRACKED_DIRTY="true"
HIST_STAMPS='[dd.mm.yyyy]'
OMB_USE_SUDO=false
OMB_DEFAULT_ALIASES="check"
#OMB_PROMPT_SHOW_PYTHON_VENV=true
OSH_CUSTOM="$XDG_CONFIG_HOME/bash/custom"

# Make dirs
OSH_CUSTOM_DIRS=(aliases completions plugins themes)
for dir in "${OSH_CUSTOM_DIRS[@]}"; do
    if [ ! -d "${OSH_CUSTOM}/$dir" ]; then
        mkdir -p "${OSH_CUSTOM}/$dir"
    fi
done
unset dir


# Completions
completions=(
    brew
    docker
    git
    go
    helm
    kubectl
    minikube
    npm
)

plugins=(
    bash-preexec
    progress
)

# Adding kubectx and kubens completions
if command -v kubectx > /dev/null 2>&1; then
    KUBECTX_FILES=(
        "$XDG_DATA_HOME/kubernetes/kubectx/completion/kubectx.bash"
        "$XDG_DATA_HOME/kubernetes/kubectx/completion/kubens.bash"
    )
    for file in ${KUBECTX_FILES[@]}; do
        filename=$(basename $file)
        filename="${filename%.*}"
        if [ ! -L "${OSH_CUSTOM}/completions/${filename}.completion.sh" ]; then
            ln -s "$file" "${OSH_CUSTOM}/completions/${filename}.completion.sh"
        fi
    done
    unset file
    completions+=(kubectx kubens)
fi

# Helmfile completion
if command -v helmfile > /dev/null 2>&1; then
    if [ ! -f "${OSH_CUSTOM}/completions/helmfile.completion.sh" ]; then
        helmfile completion bash > "${OSH_CUSTOM}/completions/helmfile.completion.sh"
    fi
    completions+=(helmfile)
fi

# Source oh-my-bash
source "$OSH"/oh-my-bash.sh
