#!/bin/sh
# Load homebrew
if [ -f /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
elif [ -f /usr/local/bin/brew ]; then
    eval "$(/usr/local/bin/brew shellenv)"
elif [ -f /home/linuxbrew/.linuxbrew/bin/brew ]; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
elif [ -f "$HOME/.linuxbrew/bin/brew" ]; then
    eval "$("$HOME/.linuxbrew/bin/brew" shellenv)"
else
    return
fi

# Aliases
alias ba='brew autoremove'
alias bc='brew cleanup'
alias bi='brew install'
alias bl='brew list'
alias bo='brew outdated'
alias bu='brew uninstall'
alias bubo='brew update && brew outdated'
alias bubu='bubo && brew upgrade'
alias bupd='brew update'
alias bupg='brew upgrade'

# Function
brews() {
    formulae=$(brew leaves | xargs brew deps --installed --for-each)
    casks=$(brew list --cask 2>/dev/null)

    green="$(tput setaf 2)"
    magenta="$(tput setaf 5)"
    cyan="$(tput setaf 6)"
    bold="$(tput bold)"
    off="$(tput sgr0)"

    printf "%s==>%s %sFormulae%s\n" "$green" "$magenta" "$bold" "$off"
    echo "$formulae" | sed "s/^\(.*\):\(.*\)$/\1${cyan}\2${off}/"
    printf "\n%s==>%s %sCasks%s\n" "$green" "$magenta" "$bold" "$off"
    echo "$casks"
}

brew_exists() {
    brew ls --versions "$@" >/dev/null 2>&1
}