[settings]
experimental = true
pin = true

[settings.npm]
bun = true

[settings.python]
uv_venv_auto = true

[settings.pipx]
uvx = true

[settings.cargo]
binstall = true

[tools]
node = { version = "latest", postinstall = "corepack enable && corepack prepare pnpm@latest --activate" }
bun = "latest"
go = "1.24.1"
php = "8.4.5"
cargo-binstall = "latest"
rust = { version = "1.85.0", profile = "default" }
java = "corretto-21"
maven = "3.9.9"
uv = "latest"
pipenv = "latest"
python = { version = "3.13", postinstall = "pip install --upgrade pip" }
"pipx:cookiecutter" = "latest"
"pipx:yamllint" = "latest"

[env]
MISE_NODE_DEFAULT_PACKAGES_FILE = "{{ env.XDG_CONFIG_HOME }}/mise/default-npm-packages"
npm_config_cache = "{{ env.XDG_CACHE_HOME }}/npm"
YARN_CACHE_FOLDER = "{{ env.XDG_CACHE_HOME }}/npm"
PNPM_HOME = "{{ env.XDG_DATA_HOME }}/pnpm"
UV_LINK_MODE = { value = "symlink", tools = true }
MISE_PYTHON_DEFAULT_PACKAGES_FILE = "{{ env.XDG_CONFIG_HOME }}/mise/default-python-packages"
MISE_GO_DEFAULT_PACKAGES_FILE = "{{ env.XDG_CONFIG_HOME }}/mise/default-go-packages"
MISE_RUBY_DEFAULT_PACKAGES_FILE = "{{ env.XDG_CONFIG_HOME }}/mise/default-gems"
MISE_RUSTUP_HOME = "{{ env.XDG_DATA_HOME }}/rustup"
MISE_CARGO_HOME = "{{ env.XDG_DATA_HOME }}/cargo"
_.path = ["{{ env.PNPM_HOME }}"]
