[settings]
cache_prune_age = "15d"
cargo.binstall = true
disable_hints = ["python_precompiled", "python_multi"]
experimental = true
go_default_packages_file = "~/.config/mise/default-go-packages"
pin = true

[settings.status]
show_env = false
show_tools = false

[settings.python]
compile = false
default_packages_file = "~/.config/mise/default-python-packages"
uv_venv_auto = true

[settings.ruby]
default_packages_file = "~/.config/mise/default-gems"

[settings.rust]
cargo_home = "/home/jacdevops/.local/share/cargo"
rustup_home = "/home/jacdevops/.local/share/rustup"

[settings.pipx]
uvx = true

[tools]
actionlint = "1.7.7"
bun = "latest"
cargo-binstall = "latest"
deno = "latest"
go = "1.24.1"
java = "openjdk-17"
maven = "3.9"
node = { version = "latest", postinstall = "corepack enable" }
php = "8.4.4"
pipenv = "latest"
python = ["3.12", "3.9"]
poetry = "2.1.1"
ruby = "3.4.2"
rust = "1.85.0"
uv = "latest"

# global NPM packages
"npm:npm-check-updates" = "latest"
"npm-run-all" = "latest"
"npm:czg" = "latest"
"git-open" = "latest"
"git-recent" = "latest"

# global cargo packages
"cargo:cargo-cache" = "latest"
"cargo:cargo-run-bin" = "latest"
"cargo:cargo-update" = "latest"

# global pipx packages
"pipx:cookiecutter" = "latest"
"pipx:poethepoet" = "latest"
"pipx:yamllint" = "latest"

[env]
npm_config_cache = { value = "~/.cache/npm", tools = true }
YARN_CACHE_FOLDER = { value = "~/.cache/npm" }
PNPM_HOME = { value = "~/.local/share/pnpm" }
PIPENV_VENV_IN_PROJECT = 1
PIPENV_NO_INHERIT = 1
PIPENV_IGNORE_VIRTUALENVS = 1
UV_LINK_MODE = { value = "symlink", tools = true }
